ARG BASE_IMAGE=pdd-workflow-desktop:playwright-1.61.1
FROM ${BASE_IMAGE}
ARG APP_VERSION=v1.0.0
ARG GIT_SHA=unknown
LABEL org.opencontainers.image.title="pdd-workflow-desktop" \
      org.opencontainers.image.version="$APP_VERSION" \
      org.opencontainers.image.revision="$GIT_SHA"
