import type { RuleSet, ScenarioDefinition } from '@work-order/domain';

export const defaultScenarioDefinitions: ScenarioDefinition[] = [
  {
    code: 'in-transit-refund',
    titlePatterns: ['在途无理由退款处理', '订单问题：在途无理由退款处理'],
    displayName: '在途无理由退款处理',
    displayOrder: 10,
    enabled: true,
    policyVersion: 1,
    requiresPdd: true,
    requiresOms: true,
    requiresTms: true,
    allowAutoSubmit: true,
  },
  {
    code: 'shipped-no-tracking-refund',
    titlePatterns: ['已发货无轨迹退款'],
    displayName: '已发货无轨迹退款',
    displayOrder: 20,
    enabled: true,
    policyVersion: 1,
    requiresPdd: true,
    requiresOms: true,
    requiresTms: true,
    allowAutoSubmit: true,
  },
  {
    code: 'abnormal-network-warning',
    titlePatterns: ['异常网点预警'],
    displayName: '异常网点预警',
    displayOrder: 30,
    enabled: true,
    policyVersion: 1,
    requiresPdd: true,
    requiresOms: true,
    requiresTms: false,
    allowAutoSubmit: true,
  },
  {
    code: 'return-refund',
    titlePatterns: ['退货退款'],
    displayName: '退货退款',
    displayOrder: 35,
    enabled: true,
    policyVersion: 2,
    requiresPdd: true,
    requiresOms: false,
    requiresTms: false,
    allowAutoSubmit: true,
  },
  {
    code: 'delivery-risk-concern',
    titlePatterns: ['消费者担忧货物无法送达'],
    displayName: '消费者担忧货物无法送达',
    displayOrder: 40,
    enabled: true,
    policyVersion: 2,
    requiresPdd: true,
    requiresOms: false,
    conditionalOms: true,
    requiresTms: false,
    conditionalTms: true,
    allowAutoSubmit: true,
  },
  {
    code: 'proactive-logistics-service',
    titlePatterns: ['物流异常主动服务'],
    displayName: '物流异常主动服务',
    displayOrder: 50,
    enabled: true,
    policyVersion: 1,
    requiresPdd: true,
    requiresOms: false,
    requiresTms: false,
    allowAutoSubmit: true,
  },
  {
    code: 'reverse-logistics-signed-refund',
    titlePatterns: ['逆向物流已签收', '逆向物流签收催退款'],
    titleMatchMode: 'contains',
    displayName: '逆向物流已签收退款',
    displayOrder: 55,
    enabled: true,
    policyVersion: 1,
    requiresPdd: true,
    requiresOms: false,
    requiresTms: false,
    allowAutoSubmit: true,
  },
  {
    code: 'intercept-recall',
    titlePatterns: ['消费者申请退款后提示拦截'],
    displayName: '消费者申请退款后提示拦截',
    displayOrder: 60,
    enabled: true,
    policyVersion: 2,
    requiresPdd: true,
    requiresOms: true,
    requiresTms: true,
    allowAutoSubmit: true,
  },
  {
    code: 'good-deed-expedited-shipping',
    titlePatterns: ['好人好事'],
    titleMatchMode: 'contains',
    displayName: '好人好事服务单-加急发货',
    displayOrder: 70,
    enabled: true,
    policyVersion: 1,
    requiresPdd: true,
    requiresOms: true,
    requiresTms: false,
    allowAutoSubmit: true,
  },
  {
    code: 'delivered-not-received',
    titlePatterns: ['消费者反馈未收到货'],
    displayName: '消费者反馈未收到货',
    displayOrder: 80,
    enabled: true,
    policyVersion: 1,
    requiresPdd: true,
    requiresOms: true,
    requiresTms: true,
    allowAutoSubmit: true,
  },
  {
    code: 'consumer-refusal',
    titlePatterns: ['消费者拒收问题处理'],
    displayName: '消费者拒收问题处理',
    displayOrder: 90,
    enabled: true,
    policyVersion: 1,
    requiresPdd: true,
    requiresOms: true,
    requiresTms: true,
    allowAutoSubmit: true,
  },
];

export const defaultRuleSet: RuleSet = {
  version: 1,
  scenarioRules: {},
  resolutionRules: {},
  warehouseCarrierRules: [
    { id: 'zhuyue-any', warehouseAliases: ['筑越仓', '筑越仓库'], carrierMode: 'any', carriers: [], enabled: true, priority: 100 },
    { id: 'jianzhuo-not-postal', warehouseAliases: ['简卓仓', '简卓仓库'], carrierMode: 'not-in', carriers: ['邮政', 'EMS'], enabled: true, priority: 90 },
    { id: 'zhongbang-not-postal', warehouseAliases: ['众邦仓', '众邦仓库'], carrierMode: 'not-in', carriers: ['邮政', 'EMS'], enabled: true, priority: 90 },
    { id: 'mingru-not-postal', warehouseAliases: ['铭如仓', '铭如仓库'], carrierMode: 'not-in', carriers: ['邮政', 'EMS'], enabled: true, priority: 90 },
    { id: 'jieyou-not-blocked', warehouseAliases: ['捷佑仓', '捷佑仓库'], carrierMode: 'not-in', carriers: ['中通', 'ZTO', '顺丰', 'SF', '邮政', 'EMS'], enabled: true, priority: 90 },
  ],
};
