ALTER SCHEMA cutover_backup_20260923 OWNER TO postgres;
ALTER SCHEMA cutover_stage_20260923 OWNER TO workorders;
ALTER FUNCTION public.enforce_current_ordinary_instance_ownership() OWNER TO postgres;
ALTER FUNCTION public.enforce_ordinary_instance_shop_ownership() OWNER TO postgres;
ALTER FUNCTION public.enforce_related_ordinary_instance_ownership() OWNER TO postgres;
ALTER FUNCTION public.enforce_work_order_ordinary_instance_shops() OWNER TO postgres;
ALTER FUNCTION public.notify_dashboard_event() OWNER TO postgres;
ALTER FUNCTION public.prevent_terminal_automatic_intervention_reopen() OWNER TO postgres;
ALTER FUNCTION public.resolve_completed_work_order_interventions() OWNER TO postgres;
ALTER FUNCTION public.sync_current_ordinary_instance_from_work_order() OWNER TO postgres;
ALTER FUNCTION public.sync_shop_schedule_state() OWNER TO postgres;
ALTER TABLE cutover_backup_20260923.audit_id_map OWNER TO postgres;
ALTER TABLE cutover_backup_20260923.before_audit_events OWNER TO postgres;
ALTER TABLE cutover_backup_20260923.before_classification_history OWNER TO postgres;
ALTER TABLE cutover_backup_20260923.before_data_corrections OWNER TO postgres;
ALTER TABLE cutover_backup_20260923.before_evidence_assets OWNER TO postgres;
ALTER TABLE cutover_backup_20260923.before_external_effects OWNER TO postgres;
ALTER TABLE cutover_backup_20260923.before_logistics_analyses OWNER TO postgres;
ALTER TABLE cutover_backup_20260923.before_manual_interventions OWNER TO postgres;
ALTER TABLE cutover_backup_20260923.before_notification_deliveries OWNER TO postgres;
ALTER TABLE cutover_backup_20260923.before_notification_outbox OWNER TO postgres;
ALTER TABLE cutover_backup_20260923.before_oms_analyses OWNER TO postgres;
ALTER TABLE cutover_backup_20260923.before_operator_commands OWNER TO postgres;
ALTER TABLE cutover_backup_20260923.before_ordinary_work_order_instances OWNER TO postgres;
ALTER TABLE cutover_backup_20260923.before_return_refunds OWNER TO postgres;
ALTER TABLE cutover_backup_20260923.before_tms_work_orders OWNER TO postgres;
ALTER TABLE cutover_backup_20260923.before_verification_locations OWNER TO postgres;
ALTER TABLE cutover_backup_20260923.before_work_orders OWNER TO postgres;
ALTER TABLE cutover_backup_20260923.before_workflow_events OWNER TO postgres;
ALTER TABLE cutover_backup_20260923.before_workflow_runs OWNER TO postgres;
ALTER TABLE cutover_backup_20260923.event_id_map OWNER TO postgres;
ALTER TABLE cutover_backup_20260923.inserted_audit_events OWNER TO postgres;
ALTER TABLE cutover_backup_20260923.inserted_classification_history OWNER TO postgres;
ALTER TABLE cutover_backup_20260923.inserted_data_corrections OWNER TO postgres;
ALTER TABLE cutover_backup_20260923.inserted_evidence_assets OWNER TO postgres;
ALTER TABLE cutover_backup_20260923.inserted_external_effects OWNER TO postgres;
ALTER TABLE cutover_backup_20260923.inserted_logistics_analyses OWNER TO postgres;
ALTER TABLE cutover_backup_20260923.inserted_manual_interventions OWNER TO postgres;
ALTER TABLE cutover_backup_20260923.inserted_notification_deliveries OWNER TO postgres;
ALTER TABLE cutover_backup_20260923.inserted_notification_outbox OWNER TO postgres;
ALTER TABLE cutover_backup_20260923.inserted_oms_analyses OWNER TO postgres;
ALTER TABLE cutover_backup_20260923.inserted_operator_commands OWNER TO postgres;
ALTER TABLE cutover_backup_20260923.inserted_ordinary_work_order_instances OWNER TO postgres;
ALTER TABLE cutover_backup_20260923.inserted_return_refunds OWNER TO postgres;
ALTER TABLE cutover_backup_20260923.inserted_tms_work_orders OWNER TO postgres;
ALTER TABLE cutover_backup_20260923.inserted_verification_locations OWNER TO postgres;
ALTER TABLE cutover_backup_20260923.inserted_work_orders OWNER TO postgres;
ALTER TABLE cutover_backup_20260923.inserted_workflow_events OWNER TO postgres;
ALTER TABLE cutover_backup_20260923.inserted_workflow_runs OWNER TO postgres;
ALTER TABLE cutover_backup_20260923.merge_report OWNER TO postgres;
ALTER TABLE cutover_stage_20260923.audit_events OWNER TO workorders;
ALTER TABLE cutover_stage_20260923.classification_history OWNER TO workorders;
ALTER TABLE cutover_stage_20260923.data_corrections OWNER TO workorders;
ALTER TABLE cutover_stage_20260923.evidence_assets OWNER TO workorders;
ALTER TABLE cutover_stage_20260923.external_effects OWNER TO workorders;
ALTER TABLE cutover_stage_20260923.logistics_analyses OWNER TO workorders;
ALTER TABLE cutover_stage_20260923.manual_interventions OWNER TO workorders;
ALTER TABLE cutover_stage_20260923.notification_deliveries OWNER TO workorders;
ALTER TABLE cutover_stage_20260923.notification_outbox OWNER TO workorders;
ALTER TABLE cutover_stage_20260923.oms_analyses OWNER TO workorders;
ALTER TABLE cutover_stage_20260923.operator_commands OWNER TO workorders;
ALTER TABLE cutover_stage_20260923.ordinary_work_order_instances OWNER TO workorders;
ALTER TABLE cutover_stage_20260923.return_refunds OWNER TO workorders;
ALTER TABLE cutover_stage_20260923.tms_work_orders OWNER TO workorders;
ALTER TABLE cutover_stage_20260923.verification_locations OWNER TO workorders;
ALTER TABLE cutover_stage_20260923.work_orders OWNER TO workorders;
ALTER TABLE cutover_stage_20260923.workflow_events OWNER TO workorders;
ALTER TABLE cutover_stage_20260923.workflow_runs OWNER TO workorders;
ALTER TABLE public.audit_events OWNER TO postgres;
ALTER SEQUENCE public.audit_events_id_seq OWNER TO postgres;
ALTER TABLE public.browser_slots OWNER TO postgres;
ALTER TABLE public.chat_analysis_jobs OWNER TO postgres;
ALTER TABLE public.chat_analysis_settings OWNER TO postgres;
ALTER TABLE public.chat_attachments OWNER TO postgres;
ALTER TABLE public.chat_cases OWNER TO postgres;
ALTER TABLE public.chat_feedback_effects OWNER TO postgres;
ALTER TABLE public.chat_snapshots OWNER TO postgres;
ALTER TABLE public.classification_history OWNER TO postgres;
ALTER TABLE public.cross_shop_order_conflicts OWNER TO postgres;
ALTER SEQUENCE public.cross_shop_order_conflicts_id_seq OWNER TO postgres;
ALTER TABLE public.data_corrections OWNER TO postgres;
ALTER TABLE public.dingtalk_daily_summaries OWNER TO postgres;
ALTER TABLE public.evidence_assets OWNER TO postgres;
ALTER TABLE public.external_effects OWNER TO postgres;
ALTER TABLE public.logistics_analyses OWNER TO postgres;
ALTER SEQUENCE public.logistics_analyses_id_seq OWNER TO postgres;
ALTER TABLE public.manual_interventions OWNER TO postgres;
ALTER TABLE public.migration_runs OWNER TO postgres;
ALTER TABLE public.notification_deliveries OWNER TO postgres;
ALTER TABLE public.notification_outbox OWNER TO postgres;
ALTER TABLE public.oms_analyses OWNER TO postgres;
ALTER SEQUENCE public.oms_analyses_id_seq OWNER TO postgres;
ALTER TABLE public.operator_commands OWNER TO postgres;
ALTER TABLE public.ordinary_work_order_instances OWNER TO postgres;
ALTER TABLE public.pdd_shop_runtime_bindings OWNER TO postgres;
ALTER TABLE public.return_refunds OWNER TO postgres;
ALTER TABLE public.rule_versions OWNER TO postgres;
ALTER SEQUENCE public.rule_versions_id_seq OWNER TO postgres;
ALTER TABLE public.scenario_definitions OWNER TO postgres;
ALTER TABLE public.schema_migrations OWNER TO postgres;
ALTER TABLE public.shop_deletion_requests OWNER TO postgres;
ALTER TABLE public.shop_identity_bindings OWNER TO postgres;
ALTER TABLE public.shop_runtime_state OWNER TO postgres;
ALTER TABLE public.shop_schedule_state OWNER TO postgres;
ALTER TABLE public.shops OWNER TO postgres;
ALTER TABLE public.sync_cursors OWNER TO postgres;
ALTER TABLE public.system_settings OWNER TO postgres;
ALTER TABLE public.tms_work_orders OWNER TO postgres;
ALTER TABLE public.verification_locations OWNER TO postgres;
ALTER TABLE public.work_orders OWNER TO postgres;
ALTER TABLE public.worker_heartbeats OWNER TO postgres;
ALTER TABLE public.workflow_checkpoints OWNER TO postgres;
ALTER TABLE public.workflow_events OWNER TO postgres;
ALTER TABLE public.workflow_runs OWNER TO postgres;
GRANT USAGE ON SCHEMA public TO workorders;
GRANT SELECT,INSERT,DELETE,UPDATE ON TABLE public.audit_events TO workorders;
GRANT ALL ON SEQUENCE public.audit_events_id_seq TO workorders;
GRANT SELECT,INSERT,DELETE,UPDATE ON TABLE public.browser_slots TO workorders;
GRANT SELECT,INSERT,DELETE,UPDATE ON TABLE public.chat_analysis_jobs TO workorders;
GRANT SELECT,INSERT,DELETE,UPDATE ON TABLE public.chat_analysis_settings TO workorders;
GRANT SELECT,INSERT,DELETE,UPDATE ON TABLE public.chat_attachments TO workorders;
GRANT SELECT,INSERT,DELETE,UPDATE ON TABLE public.chat_cases TO workorders;
GRANT SELECT,INSERT,DELETE,UPDATE ON TABLE public.chat_feedback_effects TO workorders;
GRANT SELECT,INSERT,DELETE,UPDATE ON TABLE public.chat_snapshots TO workorders;
GRANT SELECT,INSERT,DELETE,UPDATE ON TABLE public.classification_history TO workorders;
GRANT SELECT,INSERT,DELETE,UPDATE ON TABLE public.cross_shop_order_conflicts TO workorders;
GRANT ALL ON SEQUENCE public.cross_shop_order_conflicts_id_seq TO workorders;
GRANT SELECT,INSERT,DELETE,UPDATE ON TABLE public.data_corrections TO workorders;
GRANT SELECT,INSERT,DELETE,UPDATE ON TABLE public.dingtalk_daily_summaries TO workorders;
GRANT SELECT,INSERT,DELETE,UPDATE ON TABLE public.evidence_assets TO workorders;
GRANT SELECT,INSERT,DELETE,UPDATE ON TABLE public.external_effects TO workorders;
GRANT SELECT,INSERT,DELETE,UPDATE ON TABLE public.logistics_analyses TO workorders;
GRANT ALL ON SEQUENCE public.logistics_analyses_id_seq TO workorders;
GRANT SELECT,INSERT,DELETE,UPDATE ON TABLE public.manual_interventions TO workorders;
GRANT SELECT,INSERT,DELETE,UPDATE ON TABLE public.migration_runs TO workorders;
GRANT SELECT,INSERT,DELETE,UPDATE ON TABLE public.notification_deliveries TO workorders;
GRANT SELECT,INSERT,DELETE,UPDATE ON TABLE public.notification_outbox TO workorders;
GRANT SELECT,INSERT,DELETE,UPDATE ON TABLE public.oms_analyses TO workorders;
GRANT ALL ON SEQUENCE public.oms_analyses_id_seq TO workorders;
GRANT SELECT,INSERT,DELETE,UPDATE ON TABLE public.operator_commands TO workorders;
GRANT SELECT,INSERT,DELETE,UPDATE ON TABLE public.ordinary_work_order_instances TO workorders;
GRANT SELECT,INSERT,DELETE,UPDATE ON TABLE public.pdd_shop_runtime_bindings TO workorders;
GRANT SELECT,INSERT,DELETE,UPDATE ON TABLE public.return_refunds TO workorders;
GRANT SELECT,INSERT,DELETE,UPDATE ON TABLE public.rule_versions TO workorders;
GRANT ALL ON SEQUENCE public.rule_versions_id_seq TO workorders;
GRANT SELECT,INSERT,DELETE,UPDATE ON TABLE public.scenario_definitions TO workorders;
GRANT SELECT,INSERT,DELETE,UPDATE ON TABLE public.schema_migrations TO workorders;
GRANT SELECT,INSERT,DELETE,UPDATE ON TABLE public.shop_deletion_requests TO workorders;
GRANT SELECT,INSERT,DELETE,UPDATE ON TABLE public.shop_identity_bindings TO workorders;
GRANT SELECT,INSERT,DELETE,UPDATE ON TABLE public.shop_runtime_state TO workorders;
GRANT SELECT,INSERT,DELETE,UPDATE ON TABLE public.shop_schedule_state TO workorders;
GRANT SELECT,INSERT,DELETE,UPDATE ON TABLE public.shops TO workorders;
GRANT SELECT,INSERT,DELETE,UPDATE ON TABLE public.sync_cursors TO workorders;
GRANT SELECT,INSERT,DELETE,UPDATE ON TABLE public.system_settings TO workorders;
GRANT SELECT,INSERT,DELETE,UPDATE ON TABLE public.tms_work_orders TO workorders;
GRANT SELECT,INSERT,DELETE,UPDATE ON TABLE public.verification_locations TO workorders;
GRANT SELECT,INSERT,DELETE,UPDATE ON TABLE public.work_orders TO workorders;
GRANT SELECT,INSERT,DELETE,UPDATE ON TABLE public.worker_heartbeats TO workorders;
GRANT SELECT,INSERT,DELETE,UPDATE ON TABLE public.workflow_checkpoints TO workorders;
GRANT SELECT,INSERT,DELETE,UPDATE ON TABLE public.workflow_events TO workorders;
GRANT SELECT,INSERT,DELETE,UPDATE ON TABLE public.workflow_runs TO workorders;
ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public GRANT SELECT,INSERT,DELETE,UPDATE ON TABLES TO workorders;
