INSERT INTO shops (
  id,
  name,
  enabled,
  rule_version,
  expected_shop_name,
  work_order_title,
  scenario_codes,
  onboarding_status,
  onboarding_error,
  created_by,
  config_version,
  display_slot
) VALUES
  (
    'panapopo-healthcare',
    'PANAPOPO医疗器械官方旗舰店',
    true,
    1,
    'PANAPOPO医疗器械官方旗舰店',
    '订单问题：在途无理由退款处理',
    ARRAY['in-transit-refund', 'shipped-no-tracking-refund', 'abnormal-network-warning', 'return-refund', 'delivery-risk-concern', 'proactive-logistics-service', 'reverse-logistics-signed-refund', 'intercept-recall', 'good-deed-expedited-shipping', 'delivered-not-received', 'consumer-refusal'],
    'ready',
    NULL,
    'internal-bootstrap',
    13,
    0
  ),
  (
    'panapopo-medical-device',
    'PANAPOPO防护用品官方旗舰店',
    true,
    1,
    'PANAPOPO防护用品官方旗舰店',
    '订单问题：在途无理由退款处理',
    ARRAY['in-transit-refund', 'shipped-no-tracking-refund', 'abnormal-network-warning', 'return-refund', 'delivery-risk-concern', 'proactive-logistics-service', 'reverse-logistics-signed-refund', 'intercept-recall', 'good-deed-expedited-shipping', 'delivered-not-received', 'consumer-refusal'],
    'ready',
    NULL,
    'internal-bootstrap',
    10,
    1
  ),
  (
    'songteng-yazc-overseas',
    'PANAPOPO医疗保健官方旗舰店',
    true,
    1,
    'PANAPOPO医疗保健官方旗舰店',
    '订单问题：在途无理由退款处理',
    ARRAY['in-transit-refund', 'shipped-no-tracking-refund', 'abnormal-network-warning', 'return-refund', 'delivery-risk-concern', 'proactive-logistics-service', 'reverse-logistics-signed-refund', 'intercept-recall', 'good-deed-expedited-shipping', 'delivered-not-received', 'consumer-refusal'],
    'ready',
    NULL,
    'internal-bootstrap',
    12,
    2
  ),
  (
    'shop-mse1sff3-b85aa4',
    'PANAPOPO医疗保健旗舰店',
    true,
    1,
    'PANAPOPO医疗保健旗舰店',
    '订单问题：在途无理由退款处理',
    ARRAY['in-transit-refund', 'shipped-no-tracking-refund', 'abnormal-network-warning', 'return-refund', 'delivery-risk-concern', 'proactive-logistics-service', 'reverse-logistics-signed-refund', 'intercept-recall', 'good-deed-expedited-shipping', 'delivered-not-received', 'consumer-refusal'],
    'ready',
    NULL,
    'internal-bootstrap',
    13,
    3
  ),
  (
    'shop-msrd6wm5-1af283',
    'PANAPOPO医疗器具官方旗舰店',
    true,
    1,
    'PANAPOPO医疗器具官方旗舰店',
    '订单问题：在途无理由退款处理',
    ARRAY['in-transit-refund', 'shipped-no-tracking-refund', 'abnormal-network-warning', 'return-refund', 'delivery-risk-concern', 'proactive-logistics-service', 'reverse-logistics-signed-refund', 'intercept-recall', 'good-deed-expedited-shipping', 'delivered-not-received', 'consumer-refusal'],
    'ready',
    NULL,
    'internal-bootstrap',
    5,
    4
  )
ON CONFLICT (id) DO UPDATE SET
  name = EXCLUDED.name,
  enabled = EXCLUDED.enabled,
  rule_version = EXCLUDED.rule_version,
  expected_shop_name = EXCLUDED.expected_shop_name,
  work_order_title = EXCLUDED.work_order_title,
  scenario_codes = EXCLUDED.scenario_codes,
  onboarding_status = EXCLUDED.onboarding_status,
  onboarding_error = NULL,
  config_version = EXCLUDED.config_version,
  display_slot = EXCLUDED.display_slot,
  updated_at = now();
